-- /mnt/us/koreader/epubs/Thaler_ Richard H.; Imas_ Alex - The Winner's Curse_ Behavioral Economics Anomalies, Then and Now.sdr/metadata.epub.lua
return {
    ["annotations"] = {
        [1] = {
            ["chapter"] = "Chapter 4: The Endowment Effect, Loss Aversion, and Status Quo Bias",
            ["color"] = "gray",
            ["datetime"] = "2025-12-17 00:37:12",
            ["drawer"] = "lighten",
            ["page"] = "/body/DocFragment[12]/body/p[17]/text().0",
            ["pageno"] = 237,
            ["pos0"] = "/body/DocFragment[12]/body/p[17]/text().0",
            ["pos1"] = "/body/DocFragment[12]/body/p[17]/text().224",
            ["text"] = "The highest price a buyer says she would purchase a token for is taken to be her maximum willingness to pay (WTP), and the lowest price at which a seller would be willing to sell it is his lowest willingness to accept (WTA).",
        },
        [2] = {
            ["chapter"] = "Chapter 4: The Endowment Effect, Loss Aversion, and Status Quo Bias",
            ["color"] = "gray",
            ["datetime"] = "2025-12-18 10:39:31",
            ["drawer"] = "lighten",
            ["page"] = "/body/DocFragment[12]/body/p[45]/text()[1].759",
            ["pageno"] = 264,
            ["pos0"] = "/body/DocFragment[12]/body/p[45]/text()[1].759",
            ["pos1"] = "/body/DocFragment[12]/body/p[45]/text()[3].188",
            ["text"] = "The respondents were also asked to state the price reduction they would require to accept an increase of 1⁄10,000 in each of the two risks. The results were striking: 77 percent of respondents in this condition said they would refuse to buy the product at any positive price, implying an infinite WTA!",
        },
        [3] = {
            ["chapter"] = "Chapter 4: The Endowment Effect, Loss Aversion, and Status Quo Bias",
            ["color"] = "gray",
            ["datetime"] = "2025-12-18 10:46:12",
            ["drawer"] = "lighten",
            ["page"] = "/body/DocFragment[12]/body/div[3]/p[2]/text()[1].612",
            ["pageno"] = 272,
            ["pos0"] = "/body/DocFragment[12]/body/div[3]/p[2]/text()[1].612",
            ["pos1"] = "/body/DocFragment[12]/body/div[3]/p[2]/text()[1].791",
            ["text"] = "(As a wayward youth, Alex had aspired to be an artist. But his talents did not go to waste; his art pieces are now being used productively in the service of behavioral economics!)",
        },
        [4] = {
            ["chapter"] = "Chapter 6: Be Careful Before You Call Something Risk Aversion",
            ["color"] = "gray",
            ["datetime"] = "2025-12-19 23:28:29",
            ["drawer"] = "lighten",
            ["page"] = "/body/DocFragment[14]/body/p[13]/text()[4].2",
            ["pageno"] = 345,
            ["pos0"] = "/body/DocFragment[14]/body/p[13]/text()[4].2",
            ["pos1"] = "/body/DocFragment[14]/body/p[13]/text()[4].138",
            ["text"] = "This implies that Expected-Utility Theory—which defines utility over wealth—predicts that people will be risk neutral over small stakes.",
        },
        [5] = {
            ["chapter"] = "Chapter 6: Be Careful Before You Call Something Risk Aversion",
            ["color"] = "gray",
            ["datetime"] = "2026-01-02 11:53:26",
            ["drawer"] = "lighten",
            ["page"] = "/body/DocFragment[14]/body/p[16]/text()[1].458",
            ["pageno"] = 348,
            ["pos0"] = "/body/DocFragment[14]/body/p[16]/text()[1].458",
            ["pos1"] = "/body/DocFragment[14]/body/p[16]/text()[1].584",
            ["text"] = "says risk attitudes derive solely from changes in marginal utility associated with fluctuations in lifetime wealth. Hence, EUT",
        },
    },
    ["book_map_pages_per_row"] = 114,
    ["book_map_toc_depth"] = 1,
    ["cache_file_path"] = "./cache/cr3cache/Thaler_Richa-and_Now.epub.72c53b95.1.cr3",
    ["config_panel_index"] = 2,
    ["copt_b_page_margin"] = 85,
    ["copt_block_rendering_mode"] = 3,
    ["copt_cjk_width_scaling"] = 100,
    ["copt_embedded_css"] = 1,
    ["copt_embedded_fonts"] = 1,
    ["copt_font_base_weight"] = 0,
    ["copt_font_gamma"] = 15,
    ["copt_font_hinting"] = 2,
    ["copt_font_kerning"] = 3,
    ["copt_font_size"] = 29,
    ["copt_h_page_margins"] = {
        [1] = 70,
        [2] = 70,
    },
    ["copt_line_spacing"] = 100,
    ["copt_nightmode_images"] = 1,
    ["copt_render_dpi"] = 96,
    ["copt_rotation_mode"] = 0,
    ["copt_smooth_scaling"] = 0,
    ["copt_status_line"] = 1,
    ["copt_sync_t_b_page_margins"] = 1,
    ["copt_t_page_margin"] = 85,
    ["copt_view_mode"] = 0,
    ["copt_visible_pages"] = 1,
    ["copt_word_expansion"] = 5,
    ["copt_word_spacing"] = {
        [1] = 95,
        [2] = 75,
    },
    ["cre_dom_version"] = 20240114,
    ["css"] = "./data/epub.css",
    ["doc_pages"] = 1024,
    ["doc_path"] = "/mnt/us/koreader/epubs/Thaler_ Richard H.; Imas_ Alex - The Winner's Curse_ Behavioral Economics Anomalies, Then and Now.epub",
    ["doc_props"] = {
        ["authors"] = "Thaler, Richard H.; Imas, Alex",
        ["description"] = "<div> <p><strong>Named one of </strong><span style=\"font-weight: bold; font-style: italic\">Financial Times</span><strong>’s Best Books of 2025, that bestselling author Tim Hartford called \"fun\" and \"nerdy in the best way\"</strong><br><br><strong>Nobel Prize winner Richard H. Thaler and rising star economist Alex O. Imas explore the past, present, and cutting-edge future in behavioral economics in </strong><span style=\"font-weight: bold; font-style: italic\">The Winner’s Curse</span><strong>.</strong><br><br>Why do people cooperate with one another when they have no obvious motivation to do so? Why do we hold on to possessions of little value? And why is the winner of an auction so often disappointed?<br><br>Over thirty years ago, Richard H. Thaler introduced readers to behavioral economics in his seminal Anomalies column, written with collaborators including Daniel Kahneman and Amos Tversky. These provocative articles challenged the fundamental idea at the heart of economics that people are selfish, rational optimizers, and provided the foundation for what became behavioral economics. That was then.<br><br>Now, three decades later, Thaler has teamed up with economist Alex O. Imas to write a new book with an original and creative format. Each chapter starts with an original Anomaly, retaining the spirit of its time stamp. Then, shifting to the present, the authors provide updates to each, asking how the original findings have held up and how the field has evolved since then.<br><br>It turns out that the original findings not only hold up well, but they show up almost everywhere. Anomalies pop up in people’s decisions to save for retirement and how they carry outstanding credit card debt. Even experts fail to optimize. The key concept of loss aversion explains missed putts by PGA pros and the selection of which stocks to sell by portfolio managers. In this era of meme stocks and Dogecoin, it is hard to defend the view that financial markets are highly efficient. The good news, however, is that the anomalies have gotten funnier.<br><br>With both readability and rigor, <em>The Winner’s Curse</em> is for anyone, from those with a cursory understanding of economics to fellow economists. Each chapter provides a key insight into human behavior so readers learn how to better understand the choices made by their friends, colleagues, and customers, and they might just become better at making decisions themselves. <em>Only recommended for humans.</em></p></div>",
        ["identifiers"] = "uuid:0db4b7b4-2fa5-43d4-b5b5-d34d2080c3f8\
calibre:b2aeb793-9364-4310-9604-9f139a7aeb9f\
MOBI-ASIN:B0DV6HB4VM\
ISBN:9781982165116",
        ["keywords"] = "behavioral",
        ["language"] = "en",
        ["title"] = "The Winner's Curse: Behavioral Economics Anomalies, Then and Now",
    },
    ["floating_punctuation"] = 0,
    ["font_face"] = "Atkinson Hyperlegible Next",
    ["font_family_fonts"] = {},
    ["handmade_flows_edit_enabled"] = true,
    ["handmade_flows_enabled"] = false,
    ["handmade_toc_edit_enabled"] = true,
    ["handmade_toc_enabled"] = false,
    ["hide_nonlinear_flows"] = false,
    ["highlight_color"] = "gray",
    ["highlight_drawer"] = "lighten",
    ["hyph_force_algorithmic"] = false,
    ["hyph_soft_hyphens_only"] = false,
    ["hyph_trust_soft_hyphens"] = false,
    ["hyphenation"] = true,
    ["inverse_reading_order"] = false,
    ["invert_ui_layout"] = false,
    ["last_xpointer"] = "/body/DocFragment[14]/body/p[12]/text()[1].289",
    ["page_overlap_style"] = "dim",
    ["partial_md5_checksum"] = "d6ad38653b056dff0516fe504f970967",
    ["partial_rerendering"] = true,
    ["percent_finished"] = 0.3359375,
    ["readermenu_tab_index"] = 7,
    ["readest_sync"] = {
        ["meta_hash_v1"] = "1a7e2ea04fcf4e02388a06f0caf98d9e",
    },
    ["show_overlap_enable"] = false,
    ["stats"] = {
        ["authors"] = "Thaler, Richard H.; Imas, Alex",
        ["highlights"] = 5,
        ["language"] = "en",
        ["notes"] = 0,
        ["pages"] = 1024,
        ["performance_in_pages"] = {},
        ["series"] = "N/A",
        ["title"] = "The Winner's Curse: Behavioral Economics Anomalies, Then and Now",
    },
    ["summary"] = {
        ["modified"] = "2025-12-15",
        ["status"] = "reading",
    },
    ["text_lang"] = "en-US",
    ["text_lang_embedded_langs"] = true,
    ["toc_ticks_ignored_levels"] = {},
}
