-- /mnt/us/koreader/epubs/Burton G. Malkiel - A Random Walk Down Wall Street.sdr/metadata.epub.lua
return {
    ["annotations"] = {
        [1] = {
            ["chapter"] = "What Is a Random Walk?",
            ["color"] = "gray",
            ["datetime"] = "2026-01-02 11:47:53",
            ["drawer"] = "lighten",
            ["page"] = "/body/DocFragment[7]/body/section/p[9]/text().302",
            ["pageno"] = 52,
            ["pos0"] = "/body/DocFragment[7]/body/section/p[9]/text().302",
            ["pos1"] = "/body/DocFragment[7]/body/section/p[9]/text().640",
            ["text"] = "On Wall Street, the term “random walk” is an obscenity. It is an epithet coined by the academic world and hurled insultingly at the professional soothsayers. Taken to its logical extreme, it means that a blindfolded monkey throwing darts at the stock listings could select a portfolio that would do as well as one selected by the experts.",
        },
    },
    ["cache_file_path"] = "./cache/cr3cache/Burton_G._Ma-_Street.epub.798449a8.1.cr3",
    ["config_panel_index"] = 2,
    ["copt_b_page_margin"] = 50,
    ["copt_block_rendering_mode"] = 3,
    ["copt_cjk_width_scaling"] = 100,
    ["copt_embedded_css"] = 1,
    ["copt_embedded_fonts"] = 1,
    ["copt_font_base_weight"] = 0,
    ["copt_font_gamma"] = 15,
    ["copt_font_hinting"] = 2,
    ["copt_font_kerning"] = 3,
    ["copt_font_size"] = 25,
    ["copt_h_page_margins"] = {
        [1] = 50,
        [2] = 50,
    },
    ["copt_line_spacing"] = 100,
    ["copt_nightmode_images"] = 1,
    ["copt_render_dpi"] = 96,
    ["copt_rotation_mode"] = 0,
    ["copt_smooth_scaling"] = 0,
    ["copt_status_line"] = 1,
    ["copt_sync_t_b_page_margins"] = 1,
    ["copt_t_page_margin"] = 50,
    ["copt_view_mode"] = 0,
    ["copt_visible_pages"] = 1,
    ["copt_word_expansion"] = 0,
    ["copt_word_spacing"] = {
        [1] = 95,
        [2] = 75,
    },
    ["cre_dom_version"] = 20240114,
    ["css"] = "./data/epub.css",
    ["doc_pages"] = 924,
    ["doc_path"] = "/mnt/us/koreader/epubs/Burton G. Malkiel - A Random Walk Down Wall Street.epub",
    ["doc_props"] = {
        ["authors"] = "Burton G. Malkiel",
        ["description"] = "<div> <p>“A must-read for any investor.”—Browser One of the “few great investment books” (Andrew Tobias) ever written, with 2 million copies in print. In a time of rampant misinformation about ways of growing your money, Burton G. Malkiel’s gimmick-free investment guide is more necessary than ever. Whether you’re considering your first 401k contribution or contemplating retirement, the fully updated, fiftieth anniversary edition of A Random Walk Down Wall Street remains the best investment guide money can buy. Drawing on his experience as an economist, financial adviser, and successful investor, Malkiel shows why an individual who saves consistently over time and buys a diversified set of index funds can achieve above-average investment results. He addresses current investment fads and critically analyzes cryptocurrencies, NFTs, and meme stocks. Malkiel reveals how to be a tax smart investor and how to make sense of recently popular investment management techniques, including factor investing, risk parity, and ESG portfolios. Investors of every age, experience level, and risk tolerance will find the step-by-step guidance they need to protect and grow their dollars.</p></div>",
        ["identifiers"] = "google:pX1wEAAAQBAJ\
isbn:9781324035442\
calibre:188\
uuid:5ae815e7-b145-459f-b118-8d0d845205e2\
9781324035442",
        ["keywords"] = "Business & Economics\
Personal Finance\
Investing\
Money Management\
Retirement Planning",
        ["language"] = "en",
        ["title"] = "A Random Walk Down Wall Street",
    },
    ["floating_punctuation"] = 0,
    ["font_face"] = "Noto Serif",
    ["font_family_fonts"] = {},
    ["handmade_flows_edit_enabled"] = true,
    ["handmade_flows_enabled"] = false,
    ["handmade_toc_edit_enabled"] = true,
    ["handmade_toc_enabled"] = false,
    ["hide_nonlinear_flows"] = false,
    ["highlight_color"] = "gray",
    ["highlight_drawer"] = "lighten",
    ["hyph_force_algorithmic"] = false,
    ["hyph_soft_hyphens_only"] = false,
    ["hyph_trust_soft_hyphens"] = false,
    ["hyphenation"] = true,
    ["inverse_reading_order"] = false,
    ["invert_ui_layout"] = false,
    ["last_xpointer"] = "/body/DocFragment[7]/body/section/p[10]/text()[1].421",
    ["page_overlap_style"] = "dim",
    ["partial_md5_checksum"] = "1d1edab2ae679122fbc2741d7df54e3b",
    ["partial_rerendering"] = true,
    ["percent_finished"] = 0.057359307359307,
    ["readermenu_tab_index"] = 1,
    ["readest_sync"] = {
        ["meta_hash_v1"] = "651773f0c67b224a02b917140a11b0a3",
    },
    ["show_overlap_enable"] = false,
    ["stats"] = {
        ["authors"] = "Burton G. Malkiel",
        ["highlights"] = 1,
        ["language"] = "en",
        ["notes"] = 0,
        ["pages"] = 924,
        ["performance_in_pages"] = {},
        ["series"] = "N/A",
        ["title"] = "A Random Walk Down Wall Street",
    },
    ["summary"] = {
        ["modified"] = "2026-01-01",
        ["status"] = "reading",
    },
    ["text_lang"] = "en-US",
    ["text_lang_embedded_langs"] = true,
    ["toc_ticks_ignored_levels"] = {},
}
